### ISSUE TITLE
error in installation 

### ISSUE THREAD

**Issue by Hamidreza-Ramezani** [Idein/qmkl6#17]
Hello all, 

I'm trying to install your library. I encountered the following error. Do you possibly know any workaround? Thanks!

```
/home/ubuntu/qmkl6/test/fft.cpp:120:13: error: explicit specialization in non-namespace scope ‘class fft_stockham<radix, T>’
  120 |   template <>
```

**Comment by Hamidreza-Ramezani** [comment]
BTW, My gcc supports C++17.

**Comment by notogawa** [comment]
A recent gcc rejects current code. [This branch](https://github.com/Idein/qmkl6/tree/fix_specialization) will fix the error.

**Comment by Hamidreza-Ramezani** [comment]
Thanks for the update.
