### ISSUE TITLE
Cannot compile with installed library

### ISSUE THREAD

**Issue by ghost** [Idein/qmkl6#21]
tried to copy the copy.cpp, changed the library name and compiled with flags. also, set permissions to video group but always get an error on compiling: 
(both pycore library and libdrm custom library are installed as per instructions)

pi@raspberrypi:~/c++ $ g++ copy.cpp -lqmkl6
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/10/../../../aarch64-linux-gnu/libqmkl6.so: undefined reference to `drm_v3d_submit_csd'
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/10/../../../aarch64-linux-gnu/libqmkl6.so: undefined reference to `drm_v3d_wait_bo'
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/10/../../../aarch64-linux-gnu/libqmkl6.so: undefined reference to `drm_v3d_mmap_bo'
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/10/../../../aarch64-linux-gnu/libqmkl6.so: undefined reference to `drm_gem_close'
/usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/10/../../../aarch64-linux-gnu/libqmkl6.so: undefined reference to `drm_v3d_create_bo'
collect2: error: ld returned 1 exit status

any help would be highly appreciated. 
thanks.

**Comment by Terminus-IMRC** [comment]
What happens when `-ldrm_v3d` is added to the end of the command?

**Comment by ghost** [comment]
sorry for late response. thank you so much, it works now.
